SmartGarage/SmartGarage.Web/Controllers/ModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartGarage.Data;
using SmartGarage.Data.Models;
using SmartGarage.Services.Contracts;
using SmartGarage.Services.DTO;
using SmartGarage.Web.Models;
using X.PagedList;

namespace SmartGarage.Web.Controllers
{
    [Authorize(Roles = "employee")]
    public class ModelsController : Controller
    {

        private readonly IModelService modelService;
        private readonly IManufacturerService manufacturerService;
        private readonly IMapper mapper;

        public ModelsController(IModelService modelService, IMapper mapper, IManufacturerService manufacturerService)
        {
            this.modelService = modelService;
            this.mapper = mapper;
            this.manufacturerService = manufacturerService;
        }

        // GET: Models
        public async Task<IActionResult> Index(int? page)
        {
            try
            {
                var carModelDTO = await this.modelService
                    .GetAllAsync();
                var carModelView = mapper.Map<ICollection<CarModelViewModel>>(carModelDTO);
                var pageModel = await carModelView.ToPagedListAsync(page ?? 1, 10);

                return View(pageModel);
            }
            catch (Exception)
            {
                return BadRequest();
            }
            
        }

        // GET: Models/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || id <= 0)
            {
                return NotFound();
            }
            try
            {
                var carModelDto = await this.modelService
                         .GetAsync(id);
                var carModelView = mapper.Map<CarModelViewModel>(carModelDto);
            return View(carModelView);
            }
            catch(Exception)
            {
                return BadRequest();
            }
        }

        // GET: Models/Create
        public async Task<IActionResult> Create()
        {
            var manufacturerDTO = await this.manufacturerService
            .GetAllAsync();
            var manufacturerView = mapper.Map<ICollection<ManufacturerViewModel>>(manufacturerDTO);

            ViewData["ManufacturerId"] = new SelectList(manufacturerView, "ManufacturerId", "Name");
            return View();
        }

        // POST: Models/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Code,ManufacturerId")] CarModelCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var carModelDTO = mapper.Map<CarModelCreateDTO>(viewModel);
                var dto = await this.modelService.CreateAsync(carModelDTO);
                return RedirectToAction(nameof(Index));
            }
            var manufacturerDTO = await this.manufacturerService
            .GetAllAsync();
            var manufacturerView = mapper.Map<ICollection<ManufacturerViewModel>>(manufacturerDTO);

            ViewData["ManufacturerId"] = new SelectList(manufacturerView, "ManufacturerId", "Name", viewModel.ManufacturerId);
            return View(viewModel);
        }

        // GET: Models/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var carModelDto = await this.modelService
                    .GetAsync(id);
                var carModelView = mapper.Map<CarModelCreateViewModel>(carModelDto);

 
            if (carModelView == null)
            {
                return NotFound();
            }

            var manufacturerDTO = await this.manufacturerService
            .GetAllAsync();
            var manufacturerView = mapper.Map<ICollection<ManufacturerViewModel>>(manufacturerDTO);

            ViewData["ManufacturerId"] = new SelectList(manufacturerView, "ManufacturerId", "Name", carModelView.ManufacturerId);
            return View(carModelView);
        }

        // POST: Models/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ModelId,Name,Code,ManufacturerId")] CarModelCreateViewModel model)
        {
            if (id != model.ModelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var carModelDTO = mapper.Map<CarModelCreateDTO>(model);
                    await modelService.UpdateAsync(id, carModelDTO);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModelExists(model.ModelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var manufacturerDTO = await this.manufacturerService
            .GetAllAsync();
            var manufacturerView = mapper.Map<ICollection<ManufacturerViewModel>>(manufacturerDTO);

            ViewData["ManufacturerId"] = new SelectList(manufacturerView, "ManufacturerId", "Name", model.ManufacturerId);
            return View(model);
        }

        // GET: Models/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carModelDto = await this.modelService
                   .GetAsync(id);
            var carModelView = mapper.Map<CarModelViewModel>(carModelDto);
            if (carModelView == null)
            {
                return NotFound();
            }

            return View(carModelView);
        }

        // POST: Models/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.modelService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ModelExists(int id)
        {
            var carModelDto =  this.modelService
                   .GetAsync(id);
            if (carModelDto == null)
            {
                return false;
            }
            else
                return true;
        }
    }
}

SmartGarage/SmartGarage.Web/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartGarage.Data;
using SmartGarage.Services.Contracts;
using SmartGarage.Services.DTO;
using SmartGarage.Web.Models;

namespace SmartGarage.Web.Controllers
{
    [Authorize(Roles = "employee")]
    public class UsersController : Controller
    {
        private readonly SmartGarageDbContext _context;
        private readonly IUserService userService;
        private readonly IMapper mapper;
        private readonly IRoleService roleService;

        public UsersController(SmartGarageDbContext context, IMapper mapper, IUserService userService, IRoleService roleService)
        {
            _context = context;
            this.mapper = mapper;
            this.userService = userService;
            this.roleService = roleService;
        }

        // GET: Users
        
        public async Task<IActionResult> Index(string searchBy, string filter, DateTime? start, DateTime? end, string sortBy)
        {
            var userViewModel = await SelectFilterAsync(searchBy, filter, start, end);

            switch (sortBy)
            {
                case "Name desc":
                    userViewModel = userViewModel.OrderBy(v => v.FirstName).ToList();
                    break;

                case "VisitDate desc":
                    var usersFiltered = await this.userService
                              .SortUsersByVisitDate();
                    var userMapper = mapper.Map<ICollection<UserGetViewModel>>(usersFiltered);
                    return View(userMapper);
                    
                default:
                    break;
            }
            return View(userViewModel);
        }

        private async Task<ICollection<UserGetViewModel>> SelectFilterAsync(string searchBy, string filter, DateTime? start, DateTime? end)
        {
            if (searchBy == "Role" && filter != null)
            {
                var usersFiltered = await this.userService
                              .FilterUsersByRole(filter);
                var userMapper = mapper.Map<ICollection<UserGetViewModel>>(usersFiltered);
                return userMapper;
            }
            else if (searchBy == "LastName")
            {
                var usersFiltered = await this.userService
                              .FilterUsersByLastName(filter);
                var userMapper = mapper.Map<ICollection<UserGetViewModel>>(usersFiltered);
                return userMapper;
            }
            else if(searchBy == "Manufacturer")
            {
                var usersFiltered = await this.userService
                              .FilterUsersByVehicleMake(filter);
                var userMapper = mapper.Map<ICollection<UserGetViewModel>>(usersFiltered);
                return userMapper;
            }
            else if (searchBy == "Email")
            {
                var usersFiltered = await this.userService
                              .FilterUsersByEmail(filter);
                var userMapper = mapper.Map<ICollection<UserGetViewModel>>(usersFiltered);
                return userMapper;
            }
            else if (searchBy == "Phone")
            {
                var usersFiltered = await this.userService
                              .FilterUsersByPhone(filter);
                var userMapper = mapper.Map<ICollection<UserGetViewModel>>(usersFiltered);
                return userMapper;
            }
            else if (searchBy == "Model")
            {
                var usersFiltered = await this.userService
                              .FilterUsersByVehicleModel(filter);
                var userMapper = mapper.Map<ICollection<UserGetViewModel>>(usersFiltered);
                return userMapper;
            }
            else if (start != null || end != null)
            {
                var usersFiltered = await this.userService
                              .FilterUsersByVisitInRange(start, end);
                var userMapper = mapper.Map<ICollection<UserGetViewModel>>(usersFiltered);
                return userMapper;
            }

            var userDto = await this.userService
              .GetAllAsync();
            var userViewModel = mapper.Map<ICollection<UserGetViewModel>>(userDto);
            return userViewModel;

        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userDto = await this.userService
                    .GetAsync(id);
            var userView = mapper.Map<UserGetViewModel>(userDto);

            if (userView == null)
            {
                return NotFound();
            }

            return View(userView);
        }

        // GET: Users/Create
        public async Task<IActionResult> Create()
        {
            var roleDto = await this.roleService
              .GetAllAsync();
            var roleViewModel = mapper.Map<ICollection<RoleViewModel>>(roleDto);

            ViewData["RoleId"] = new SelectList(roleViewModel.ToList(), "RoleId", "Name");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,PhoneNumber,Email,RoleId")] UserCreateModelView userCreateViewModel)
        {
            if (ModelState.IsValid)
            {
                var carModelDTO = mapper.Map<UserCreateDTO>(userCreateViewModel);
                var dto = await this.userService.CreateAsync(carModelDTO);
                return RedirectToAction(nameof(Index));
            }
            return View(userCreateViewModel);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var userDto = await this.userService
                    .GetAsync(id);
            var userView = mapper.Map<UserUpdateViewModel>(userDto);

            if (userView == null)
            {
                return NotFound();
            }
            return View(userView);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,PhoneNumber,Email")] UserUpdateViewModel userViewModel)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var useDTO = mapper.Map<UserDTO>(userViewModel);
                    var dto = await userService.UpdateAsync(id, useDTO);

                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userViewModel);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userDto = await this.userService
                    .GetAsync(id);
            var userView = mapper.Map<UserGetViewModel>(userDto);
            if (userView == null)
            {
                return NotFound();
            }

            return View(userView);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.userService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

SmartGarage/SmartGarage.Web/Views/Shared/_HomeLayout.cshtml
@model CounterViewModel
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartGarage.Web</title>

    <!-- Favicons -->
    <link href="~/favicon.ico" rel="icon">
    <link href="~/apple-touch-icon.png" rel="apple-touch-icon">


    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- Custom CSS File -->
    <link href="~/css/mystyle.css" rel="stylesheet">
    <link href="~/css/mystyleHomePage.css" rel="stylesheet">
</head>
<body>
    <!-- ======= Top Bar ======= -->
    <div id="topbar" class="d-none d-lg-flex align-items-center fixed-top">
        <div class="container d-flex">
            <div class="contact-info mr-auto">
                <i class="icofont-envelope"></i> <a href="mailto:smartgarageruslanirina@gmail.com">smartgarageruslanirina@gmail.com</a>
                <i class="icofont-phone"></i> +359 888 000 888
            </div>
            <div class="social-links">
                <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
                <a href="#" class="facebook"><i class="icofont-facebook"></i></a>
                <a href="#" class="instagram"><i class="icofont-instagram"></i></a>
                <a href="#" class="skype"><i class="icofont-skype"></i></a>
                <a href="#" class="linkedin"><i class="icofont-linkedin"></i></a>
            </div>
        </div>
    </div>
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center justify-content-between">

            <!-- Uncomment below if you prefer to use an image logo -->
            <div></div>

            <nav class="nav-menu d-none d-lg-block">
                <ul>
                    <li class="active"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Services" asp-action="Index">Auto Services</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="drop-down">
                            <a href="">My Services</a>
                            <ul>
                                <li><a asp-area="" asp-controller="Customers" asp-action="Vehicles">My Vehicles</a></li>
                                <li><a asp-area="" asp-controller="Customers" asp-action="Services">My Services</a></li>
                                <li><a asp-area="" asp-controller="Customers" asp-action="Visits">My Visits</a></li>
                            </ul>
                        </li>
                    }

                    @if (User.IsInRole("employee"))
                    {
                        <li class="drop-down">
                            <a href="">Administration</a>
                            <ul>
                                <li><a asp-area="" asp-controller="Manufacturers" asp-action="Index">Manufacturers</a></li>
                                <li><a asp-area="" asp-controller="Models" asp-action="Index">Models</a></li>
                                <li><a asp-area="" asp-controller="Services" asp-action="Index">Services</a></li>
                                <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                                <li><a asp-area="" asp-controller="Vehicles" asp-action="Index">Vehicles</a></li>
                                <li><a asp-area="" asp-controller="VehicleTypes" asp-action="Index">Vehicle Types</a></li>
                                <li><a asp-area="" asp-controller="Visits" asp-action="Index">Visits</a></li>
                                <li><a asp-area="" asp-controller="VisitStatuses" asp-action="Index">Visit Statuses</a></li>
                            </ul>
                        </li>
                    }

                </ul>
            </nav><!-- .nav-menu -->

            <partial name="_LoginPartial.cshtml" />

        </div>
    </header><!-- End Header -->
    <!--Statistics-->
    @*<div class="counter">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                    <div class="tracks">
                        <p class="counter-count">@Model.ServicesCount</p>
                        <p class="tracks-p">Tracks</p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                    <div class="artists">
                        <p class="counter-count">@Model.CustomersCount</p>
                        <p class="artists-p">Artists</p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                    <div class="playlists">
                        <p class="counter-count">@Model.VehiclesCount</p>
                        <p class="playlists-p">Playlists</p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                    <div class="users">
                        <p class="counter-count">@Model.VisitsCount</p>
                        <p class="users-p">Users</p>
                    </div>
                </div>
            </div>
        </div>
    </div>*@


    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center justify-content-center">
        <div class="container" data-aos="fade-up">

            <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
                <div class="col-xl-6 col-lg-8">
                    <a href='@Url.Action("Index", "Home")'>
                        <img src="~/Images/Smart-Garage-Logo.png" class="img-fluid" />
                    </a>
                    <h2>Your vehicle, our mission.</h2>
                </div>
            </div>

            <div class="row mt-5 justify-content-center" data-aos="zoom-in" data-aos-delay="250">
                <div class="col-xl-2 col-md-4 col-6">
                    <div class="icon-box">
                        <i class="ri-store-line"></i>
                        <h3>
                            <a>
                                <p>@Model.ServicesCount</p>
                                <p>Services</p>
                            </a>
                        </h3>
                    </div>
                </div>
                <div class="col-xl-2 col-md-4 col-6 ">
                    <div class="icon-box">
                        <i class="ri-bar-chart-box-line"></i>
                        <h3>
                            <a>
                                <p>@Model.CustomersCount</p>
                                <p>Customers</p>
                            </a>
                        </h3>
                    </div>
                </div>
                <div class="col-xl-2 col-md-4 col-6 mt-4 mt-md-0">
                    <div class="icon-box">
                        <i class="ri-calendar-todo-line"></i>
                        <h3>
                            <a>
                                <p>@Model.VehiclesCount</p>
                                <p>Vehicles</p>
                            </a>
                        </h3>
                    </div>
                </div>
                <div class="col-xl-2 col-md-4 col-6 mt-4 mt-xl-0">
                    <div class="icon-box">
                        <i class="ri-paint-brush-line"></i>
                        <h3>
                            <a>
                                <p>@Model.VisitsCount</p>
                                <p>Visits</p>
                            </a>
                        </h3>
                    </div>
                </div>
            </div>

        </div>
    </section><!-- End Hero -->

    <div class="container content">
        <main role="main" class="pb-3">

            @RenderBody()

        </main>
    </div>

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer fixed-bottom">

        <div class="container">
            <div class="copyright">
                &copy; 2021 - <span>SmartGarage</span>. All Rights Reserved
            </div>
        </div>
    </footer>
    <!-- End Footer -->

    <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/venobox/venobox.min.js"></script>
    <script src="~/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="~/assets/vendor/counterup/counterup.min.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

    <!-- Counter-->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>

    @RenderSection("Scripts", required: false)
</body>
</html>