SmartGarage/SmartGarage.Web/Models/ServiceViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SmartGarage.Web.Models
{
    public class ServiceViewModel
    {
        public ServiceViewModel()
        {
            this.VehicleTypes = new List<int>();
            this.Currency = "EUR";
        }

        public int ServiceId { get; set; }

        public string Name { get; set; }

        public ICollection<int> VehicleTypes { get; set; }

        public decimal Price { get; set; }

        public string Currency { get; set; }
    }
}

SmartGarage/SmartGarage.Web/Models/VehicleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SmartGarage.Web.Models
{
    public class VehicleViewModel
    {
        public VehicleViewModel()
        {
            this.Visits = new List<int>();
        }

        public int VehicleId { get; set; }

        public string Vin { get; set; }

        public string RegistrationPlate { get; set; }

        public int OwnerId { get; set; }

        public int ModelId { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/yyyy}")]
        public DateTime Year { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime CreatedOn { get; set; }

        public int VehicleTypeId { get; set; }

        public string VehicleType { get; set; }

        public ICollection<int> Visits { get; set; }
    }
}

SmartGarage/SmartGarage.Web/Models/VisitViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SmartGarage.Web.Models
{
    public class VisitViewModel
    {
        public VisitViewModel()
        {
            this.VisitServices = new HashSet<ServiceViewModel>();
        }

        public int VisitId { get; set; }

        public int VehicleId { get; set; }

        public string VisitStatus { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime ArriveDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime DepartureDate { get; set; }

        public ICollection<ServiceViewModel> VisitServices { get; set; }
    }
}

SmartGarage/SmartGarage.Web/Controllers/CustomersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmartGarage.Services.Contracts;
using SmartGarage.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;


namespace SmartGarage.Web.Controllers
{
    [Authorize()]
    public class CustomersController : Controller
    {
        private readonly ICustomerServices customerServices;
        private readonly IPdfGeneratorService pdfGeneratorService;
        private readonly IMapper mapper; 

        public CustomersController(ICustomerServices customerServices, IMapper mapper, IPdfGeneratorService pdfGeneratorService)
        {
            this.customerServices = customerServices;
            this.mapper = mapper;
            this.pdfGeneratorService = pdfGeneratorService;
        }

        public async Task<IActionResult> Vehicles()
        {
            var username = User.Identity.Name; 
            var vehiclesDto = await this.customerServices.GetAllVehicles(username);
            var manufacturerView = mapper.Map<ICollection<CustomerVehiclesViewModel>>(vehiclesDto);


            return View(manufacturerView);
        }

        public async Task<IActionResult> Services(int? page, string currentFilter, string searchString, DateTime? filterDate)
        {
            var username = User.Identity.Name;

            if (searchString != null || filterDate != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.currentFilter = searchString;

            try
            {

                if(searchString == null && filterDate != null)
                {
                    var customerDTO = await this.customerServices.FilterServicesByDate(username, filterDate);
                    var viewModel = mapper.Map<ICollection<CustomerGetAllServicesViewModel>>(customerDTO);
                    var filterByRegPlate = viewModel.Where(s => s.ArriveDate == filterDate);
                    var filterModel = await filterByRegPlate.ToPagedListAsync(page ?? 1, 2);
                    return View(filterModel);
                }

                else if (searchString != null && filterDate == null)
                {
                    var customerDTO = await this.customerServices.FilterServicesByRegPlate(username, searchString);
                    var viewModel = mapper.Map<ICollection<CustomerGetAllServicesViewModel>>(customerDTO);
                    var filterByRegPlate = viewModel.Where(s => s.VehicleRegistrationPlate == searchString);
                    var filterModel = await filterByRegPlate.ToPagedListAsync(page ?? 1, 2);
                    return View(filterModel);
                }
                else if (searchString != null && filterDate != null)
                {
                    var customerDTO = await this.customerServices.FilterServicesByRegPlateAndDate(username, searchString, filterDate);
                    var viewModel = mapper.Map<ICollection<CustomerGetAllServicesViewModel>>(customerDTO);
                    var filterByRegPlate = viewModel.Where(s => s.VehicleRegistrationPlate == searchString);
                    var filterModel = await filterByRegPlate.ToPagedListAsync(page ?? 1, 2);
                    return View(filterModel);
                }

                var customerGetAllServicesDTO = await this.customerServices.GetAllServices(username);
                var customerView = mapper.Map<ICollection<CustomerGetAllServicesViewModel>>(customerGetAllServicesDTO);
                var pageModel = await customerView.ToPagedListAsync(page ?? 1, 2);
                return View(pageModel);
            }
            catch (Exception)
            {
                return BadRequest();
            }   
        }

        public async Task<IActionResult> Visits(string currency, bool generatePdf)
        {
            try
            {
                var username = User.Identity.Name;
                var customerGetAllVisitsDTO = await this.customerServices.GetAllVisitsReport(username, currency);
                var customerView = mapper.Map<CustomerGetAllVisitsViewModel>(customerGetAllVisitsDTO);
                if(generatePdf == true)
                {
                    return (this.pdfGeneratorService.GeneratePdfForAllVisitsOfCustomer(customerGetAllVisitsDTO));
                }
                return View(customerView);
            }
            catch(Exception)
            {
                return BadRequest();
            }
        }

        public async Task<IActionResult> VisitDetails(int? id, string currency, bool generatePdf)
        {
            var username = User.Identity.Name;
            //try
            //{
                if (currency != null)
                {
                    var GetAllVisitsDTO = await this.customerServices.GetVisitReportByIdAndCurrency(username, id, currency);
                    
                    if(generatePdf == true)
                    {
                        return (this.pdfGeneratorService.GeneratePdfForOneVisit(GetAllVisitsDTO));
                    }
                    var viewModel = mapper.Map<CustomerGetVisitViewModel>(GetAllVisitsDTO);
                    return View(viewModel);
                }

                var customerGetAllVisitsDTO = await this.customerServices.GetVisitReportById(username, id);
                if(generatePdf == true)
                {
                    return (this.pdfGeneratorService.GeneratePdfForOneVisit(customerGetAllVisitsDTO));
                }
                var customerView = mapper.Map<CustomerGetVisitViewModel>(customerGetAllVisitsDTO);
                return View(customerView);
            //}
            //catch(Exception)
            //{
            //    return BadRequest();
            //}
        }


        public IActionResult CreateDocument()
        {
            var username = User.Identity.Name;
    

            var customerGetAllVisitsDTO = this.customerServices.GetAllVisitsReport(username, "EUR");

            return (this.pdfGeneratorService.GeneratePdfForAllVisitsOfCustomer(customerGetAllVisitsDTO.Result));
        }

    }
}

SmartGarage/SmartGarage.Web/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using CustomExceptions.Exceptions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmartGarage.Services.Contracts;
using SmartGarage.Services.DTO;
using SmartGarage.Web.Models;
using X.PagedList;

namespace SmartGarage.Web.Controllers
{
    public class ServicesController : Controller
    {
        private readonly IMapper mapper;
        private readonly IServiceService serviceService;
        private readonly IVehicleTypeService vehicleTypeService;

        public ServicesController(IMapper mapper, IServiceService serviceService, IVehicleTypeService vehicleTypeService)
        {
            this.mapper = mapper;
            this.serviceService = serviceService;
            this.vehicleTypeService = vehicleTypeService;
        }

        public async Task<IActionResult> Index(int? page, string name, decimal price)
        {
            var serviceViewModel = await FilterAsync(name, price, page);

            if (serviceViewModel == null)
                return NoContent(); 
            else
                return View(serviceViewModel);
        }

        public async Task<IActionResult> Details(int id, int? page)
        {
            var itemsDto = await this.serviceService.GetServiceAndTypeAsync(id);

            if (itemsDto.Count == 0)
            {
                return NotFound();
            }

            var itemsView = mapper.Map<ICollection<ServiceVehicleTypeViewModel>>(itemsDto);
            var pageModel = await itemsView.ToPagedListAsync(page ?? 1, 10);

            return View(pageModel);
        }

        private async Task<IPagedList<ServiceViewModel>> FilterAsync(string name, decimal price, int? page)
        {
            if (name != null && price > 0)
            {
                var servicesFiltered = await GetByNameAndPriceAsync(name, price, page);

                return servicesFiltered;
            }
            else if (name == null && price > 0)
            {
                var servicesFiltered = await GetByPriceAsync(price, page);

                return servicesFiltered;
            }
            else if (name != null && price == 0)
            {
                var servicesFiltered = await GetByNameAsync(name, page);

                return servicesFiltered;
            }

            var servicesDto = await this.serviceService.GetAllAsync();

            var servicesView = mapper.Map<ICollection<ServiceViewModel>>(servicesDto);
            var pageModel = await servicesView.ToPagedListAsync(page ?? 1, 10);

            return pageModel;
        }

        private async Task<IPagedList<ServiceViewModel>> GetByNameAndPriceAsync(string name, decimal price, int? page)
        {
            var itemsDto = await this.serviceService.GetByNameAndPriceAsync(name, price);

            if (itemsDto.Count == 0)
                return null;

            var itemsView = mapper.Map<ICollection<ServiceViewModel>>(itemsDto);
            var pageModel = await itemsView.ToPagedListAsync(page ?? 1, 10);

            return pageModel;
        }

        private async Task<IPagedList<ServiceViewModel>> GetByNameAsync(string name, int? page)
        {
            var itemsDto = await this.serviceService.GetByNameAsync(name);

            if (itemsDto.Count == 0)
                return null;

            var itemsView = mapper.Map<ICollection<ServiceViewModel>>(itemsDto);
            var pageModel = await itemsView.ToPagedListAsync(page ?? 1, 10);

            return pageModel;
        }

        private async Task<IPagedList<ServiceViewModel>> GetByPriceAsync(decimal price, int? page)
        {
            var itemsDto = await this.serviceService.GetByPriceAsync(price);

            if (itemsDto.Count == 0)
                return null;

            var itemsView = mapper.Map<ICollection<ServiceViewModel>>(itemsDto);
            var pageModel = await itemsView.ToPagedListAsync(page ?? 1, 10);

            return pageModel;
        }

        [Authorize(Roles = "employee")]
        public async Task<IActionResult> Create()
        {
            var serviceView = new ServiceCreateViewModel();
            serviceView.VehicleTypes = await this.vehicleTypeService.GetAllAsync();

            return View(serviceView);
        }

        [HttpPost]
        [Authorize(Roles = "employee")]
        public async Task<IActionResult> Create(ServiceCreateViewModel service, List<int> types)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var serviceDto = mapper.Map<ServiceCreateDTO>(service);

                    var newService = await this.serviceService.CreateAsync(serviceDto, types);

                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return NotFound();
                }
            }

            return View(service);
        }

        [Authorize(Roles = "employee")]
        public async Task<IActionResult> Edit(int id)
        {
            var service = await this.serviceService.GetAsync(id);

            if (service == null)
            {
                return NotFound();
            }

            var serviceView = mapper.Map<ServiceUpdateViewModel>(service);
            serviceView.VehicleTypes = await this.vehicleTypeService.GetAllAsync(); 

            return View(serviceView);
        }

        [HttpPost]
        [Authorize(Roles = "employee")]
        public async Task<IActionResult> Edit(int id, ServiceUpdateViewModel service, List<int> types)
        {
            if (id != service.ServiceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var serviceDto = mapper.Map<ServiceUpdateDTO>(service);

                    await this.serviceService.UpdateAsync(id, serviceDto, types);
                }
                catch
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(service);
        }

        [Authorize(Roles = "employee")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var service = await this.serviceService.GetAsync(id);

                var serviceView = mapper.Map<ServiceUpdateViewModel>(service);

                return View(serviceView);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch
            {
                return Conflict();
            }
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "employee")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await this.serviceService.DeleteAsync(id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

SmartGarage/SmartGarage.Web/Views/Customers/Services.cshtml
@model IPagedList<CustomerGetAllServicesViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Services</h1>
@using (Html.BeginForm("Services", "Customers", FormMethod.Get))
{
    <b class=" font-weight-bold">Registr Plate: </b>
    @Html.TextBox("searchString", ViewBag.currentFilter as string)
<br />
<b class=" font-weight-bold">Arrival Date: </b>
    @Html.TextBox("filterDate")
<br />
    <input type="submit" value="Filter" />
    <a class="btn btn-outline-secondary btn-sm" asp-action="Services"> Back to full list</a>
}
<br />
<div class="card-deck">
    @foreach (var item in Model)
    {
        <div class="card">
            <div class="card-body">
                <h4 class="card-title text-info font-weight-bolder">@Html.DisplayFor(modelItem => item.VehicleModelName)</h4>
                <p class="card-text">Arrivind Date: @Html.DisplayFor(modelItem => item.ArriveDate)</p>
                <p class="card-text font-weight-bolder">Registration Plate: @Html.DisplayFor(modelItem => item.VehicleRegistrationPlate)</p>
                <p class="card-text">Visit Status: @Html.DisplayFor(modelItem => item.VisitStatusName)</p>
                <table class="table border-line">
                    <thead>
                        <tr>
                            <th>
                                ServiceId
                            </th>
                            <th>
                                Service Price
                            </th>
                            <th>
                                Service Name
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr>

                            <td>
                                @foreach (var list in item.ServicesId)
                                {
                                    <br>
                                    @Html.DisplayFor(modelItem => list)
                                    <br>
                                }
                            </td>
                            <td>
                                @foreach (var list in item.ServicePrice)
                                {
                                    <br>
                                    @Html.DisplayFor(modelItem => list)
                                    <br>

                                }
                            </td>
                            <td>
                                @foreach (var list in item.ServiceName)
                                {
                                    <br>
                                    @Html.DisplayFor(modelItem => list)
                                    <br>
                                }
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    }
</div>

@Html.PagedListPager(Model,
   page => Url.Action("Services", new { page, currentFilter = ViewBag.CurrentFilter }),
   new X.PagedList.Web.Common.PagedListRenderOptionsBase
   {
       DisplayLinkToIndividualPages = true,
       DisplayPageCountAndCurrentLocation = false,
       MaximumPageNumbersToDisplay = 10,
       LiElementClasses = new string[] { "page-item" },
       PageClasses = new string[] { "page-link" },
   })

SmartGarage/SmartGarage.Web/Views/Customers/Vehicles.cshtml
@model IEnumerable<CustomerVehiclesViewModel>

@{
    ViewData["Title"] = "Vehicles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1 class="text-white">Vehicles</h1>


<table class="table">
        <thead class="text-white">
            <tr>
                <th>
                 VehicleId
                </th>
                <th>
                 Manufacturer
                </th>
                <th>
                 Model
                </th>
                <th>
                 Registration Plate 
                </th>
                <th>
                 Year 
                </th>
                <th>
                 Vin
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody class="text-white">
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.VehicleId)
                </td>
                <th>
                    @Html.DisplayFor(modelItem => item.ModelManufacturerName)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.ModelName)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.RegistrationPlate)
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.VehicleYear)
                </td>
                <th>
                    @Html.DisplayFor(modelItem => item.Vin)
                </th>
            </tr>
            }
        </tbody>
    </table>

SmartGarage/SmartGarage.Web/Views/Customers/VisitDetails.cshtml
@model CustomerGetVisitViewModel
@{
    ViewData["Title"] = "VisitDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
    <h3 class="card-header">Visit</h3>
    <a class="btn btn-info" asp-area="" asp-controller="Customers" asp-action="Visits">Back To My Visits</a>
    <div class="card-body">
        @using (Html.BeginForm("VisitDetails", "Customers", FormMethod.Get))
        {
            <b class=" font-weight-bold">Change Currency: </b> @Html.TextBox("currency")
            <input type="submit" value="Submit" />

            <div class="form-check form-check-inline">
                @Html.CheckBox("generatePdf", "True") <text>GeneratePDF</text>
            </div>
        }


        <h4 class="card-title">@Html.DisplayFor(modelItem => Model.FirstName) @Html.DisplayFor(modelItem => Model.LastName)</h4>
        <p class="card-text font-weight-bold">@Html.DisplayFor(modelItem => Model.Email).</p>
        <p class="text-info font-weight-bold"> Model: @Html.DisplayFor(modelItem => Model.VehicleModelName).</p>
        <p class="card-text font-weight-bolder">Arrive Date: @Html.DisplayFor(modelItem => Model.ArriveDate).</p>
        <p class="card-text">Vin: @Html.DisplayFor(modelItem => Model.VehicleVin).</p>
        <p class="text-info font-weight-bold"> Status: @Html.DisplayFor(modelItem => Model.VisitStatusName).</p>
        <p class="text-danger font-weight-bold"> Status:Price: @Html.DisplayFor(modelItem => Model.VisitCost) @Html.DisplayFor(modelItem => Model.VisitCurrencyPrice)</p>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        Service
                    </th>
                    <th>
                        Currency
                    </th>
                    <th>
                        Price
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ServiceDTOs)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <th>
                            @Html.DisplayFor(modelItem => item.Currency)
                        </th>
                        <th>
                            @Html.DisplayFor(modelItem => item.Price)
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

SmartGarage/SmartGarage.Web/Views/Customers/Visits.cshtml
@model CustomerGetAllVisitsViewModel

@{
    ViewData["Title"] = "Visits";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Visits</h2>
@using (Html.BeginForm("Visits", "Customers", FormMethod.Get))
{
    <b class=" font-weight-bold">Change Currency: </b> @Html.TextBox("currency")
    <br />
    <input type="submit" value="Submit" />
    <a class="btn btn-outline-secondary btn-sm" asp-action="Visits"> Back to full list</a>
    <div class="form-check form-check-inline">
        @Html.CheckBox("generatePdf", "True") <text>GeneratePDF</text>
    </div>
}

<div class="bd-example">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            @for (int i = 0; i < Model.CustomerGetVisitDTOs.Count; i++)
            {
                <li data-target="#carouselExampleCaptions" data-slide-to="@i"></li>
                @*<li data-target="#carouselExampleCaptions" data-slide-to="@i"></li>*@
            }
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img src="~/Images/green_gray_color_153734_1366x768.jpg" alt="Alternate Text" /> @*First Image*@
            <div class="carousel-caption d-none d-md-block">
                <h4 class="text-info font-weight-bold">Summary:</h4>
                <h4 class="text-warning font-weight-bold ">The cost of all visits: @Html.DisplayFor(modelItem => Model.Currency): @Html.DisplayFor(modelItem => Model.FullPrice)</h4>
                <h3 class="text-danger font-weight-bold">Click the arrow and search all your visits!</h3>
                <h3><br /></h3>
                <h3><br /></h3>
                <h3><br /></h3>
                <h3><br /></h3>
                <h3><br /></h3>
                <h3><br /></h3>
                <h3><br /></h3>
            </div>
            </div>
            @foreach (var item in Model.CustomerGetVisitDTOs)
            {
                <div class="carousel-item ">
                    <img src="~/Images/green_gray_color_153734_1366x768.jpg" alt="Alternate Text" />
                    <div class="carousel-caption d-none d-md-block">

                        <p class="text-warning font-weight-bold ">Vehicle: @Html.DisplayFor(modelItem => item.VehicleModelName) /Vin: @Html.DisplayFor(modelItem => item.VehicleVin)</p>
                        <p class="font-weight-bold ">Arrive date: @Html.DisplayFor(modelItem => item.ArriveDate) / Status: @Html.DisplayFor(modelItem => item.VisitStatusName)</p>
                        <p class="text-danger font-weight-bold ">Visit cost: @Html.DisplayFor(modelItem => item.VisitCost)  @Html.DisplayFor(modelItem => item.VisitCurrencyPrice)</p>
                        <a class="font-weight-bolder text-info" asp-action="VisitDetails" asp-route-id="@item.VisitId">Click For Details</a>
                        <table class="table">
                            <thead>
                                <tr class="text-warning font-weight-bolder">
                                    <th>
                                        Service Name
                                    </th>
                                    <th>
                                        Currency
                                    </th>
                                    <th>
                                        Price
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var list in item.ServiceDTOs)
                                {
                                    <tr class="text-warning">
                                        <td>
                                            @Html.DisplayFor(modelItem => list.Name)
                                        </td>
                                        <th>
                                            @Html.DisplayFor(modelItem => list.Currency)
                                        </th>
                                        <th>
                                            @Html.DisplayFor(modelItem => list.Price)
                                        </th>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>

            }

        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>