SmartGarage/SmartGarage.Web/Models/ServiceViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SmartGarage.Web.Models
{
    public class ServiceViewModel
    {
        public ServiceViewModel()
        {
            this.VehicleTypes = new List<int>();
            this.Currency = "EUR";
        }

        public int ServiceId { get; set; }

        public string Name { get; set; }

        public ICollection<int> VehicleTypes { get; set; }

        public decimal Price { get; set; }

        public string Currency { get; set; }
    }
}

SmartGarage/SmartGarage.Web/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using CustomExceptions.Exceptions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmartGarage.Services.Contracts;
using SmartGarage.Services.DTO;
using SmartGarage.Web.Models;
using X.PagedList;

namespace SmartGarage.Web.Controllers
{
    public class ServicesController : Controller
    {
        private readonly IMapper mapper;
        private readonly IServiceService serviceService;
        private readonly IVehicleTypeService vehicleTypeService;

        public ServicesController(IMapper mapper, IServiceService serviceService, IVehicleTypeService vehicleTypeService)
        {
            this.mapper = mapper;
            this.serviceService = serviceService;
            this.vehicleTypeService = vehicleTypeService;
        }

        public async Task<IActionResult> Index(int? page, string name, decimal price)
        {
            var serviceViewModel = await FilterAsync(name, price, page);

            if (serviceViewModel == null)
                return NoContent(); 
            else
                return View(serviceViewModel);
        }

        public async Task<IActionResult> Details(int id, int? page)
        {
            var itemsDto = await this.serviceService.GetServiceAndTypeAsync(id);

            if (itemsDto.Count == 0)
            {
                return NotFound();
            }

            var itemsView = mapper.Map<ICollection<ServiceVehicleTypeViewModel>>(itemsDto);
            var pageModel = await itemsView.ToPagedListAsync(page ?? 1, 10);

            return View(pageModel);
        }

        private async Task<IPagedList<ServiceViewModel>> FilterAsync(string name, decimal price, int? page)
        {
            if (name != null && price > 0)
            {
                var servicesFiltered = await GetByNameAndPriceAsync(name, price, page);

                return servicesFiltered;
            }
            else if (name == null && price > 0)
            {
                var servicesFiltered = await GetByPriceAsync(price, page);

                return servicesFiltered;
            }
            else if (name != null && price == 0)
            {
                var servicesFiltered = await GetByNameAsync(name, page);

                return servicesFiltered;
            }

            var servicesDto = await this.serviceService.GetAllAsync();

            var servicesView = mapper.Map<ICollection<ServiceViewModel>>(servicesDto);
            var pageModel = await servicesView.ToPagedListAsync(page ?? 1, 10);

            return pageModel;
        }

        private async Task<IPagedList<ServiceViewModel>> GetByNameAndPriceAsync(string name, decimal price, int? page)
        {
            var itemsDto = await this.serviceService.GetByNameAndPriceAsync(name, price);

            if (itemsDto.Count == 0)
                return null;

            var itemsView = mapper.Map<ICollection<ServiceViewModel>>(itemsDto);
            var pageModel = await itemsView.ToPagedListAsync(page ?? 1, 10);

            return pageModel;
        }

        private async Task<IPagedList<ServiceViewModel>> GetByNameAsync(string name, int? page)
        {
            var itemsDto = await this.serviceService.GetByNameAsync(name);

            if (itemsDto.Count == 0)
                return null;

            var itemsView = mapper.Map<ICollection<ServiceViewModel>>(itemsDto);
            var pageModel = await itemsView.ToPagedListAsync(page ?? 1, 10);

            return pageModel;
        }

        private async Task<IPagedList<ServiceViewModel>> GetByPriceAsync(decimal price, int? page)
        {
            var itemsDto = await this.serviceService.GetByPriceAsync(price);

            if (itemsDto.Count == 0)
                return null;

            var itemsView = mapper.Map<ICollection<ServiceViewModel>>(itemsDto);
            var pageModel = await itemsView.ToPagedListAsync(page ?? 1, 10);

            return pageModel;
        }

        [Authorize(Roles = "employee")]
        public async Task<IActionResult> Create()
        {
            var serviceView = new ServiceCreateViewModel();
            serviceView.VehicleTypes = await this.vehicleTypeService.GetAllAsync();

            return View(serviceView);
        }

        [HttpPost]
        [Authorize(Roles = "employee")]
        public async Task<IActionResult> Create(ServiceCreateViewModel service, List<int> types)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var serviceDto = mapper.Map<ServiceCreateDTO>(service);

                    var newService = await this.serviceService.CreateAsync(serviceDto, types);

                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return NotFound();
                }
            }

            return View(service);
        }

        [Authorize(Roles = "employee")]
        public async Task<IActionResult> Edit(int id)
        {
            var service = await this.serviceService.GetAsync(id);

            if (service == null)
            {
                return NotFound();
            }

            var serviceView = mapper.Map<ServiceUpdateViewModel>(service);
            serviceView.VehicleTypes = await this.vehicleTypeService.GetAllAsync(); 

            return View(serviceView);
        }

        [HttpPost]
        [Authorize(Roles = "employee")]
        public async Task<IActionResult> Edit(int id, ServiceUpdateViewModel service, List<int> types)
        {
            if (id != service.ServiceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var serviceDto = mapper.Map<ServiceUpdateDTO>(service);

                    await this.serviceService.UpdateAsync(id, serviceDto, types);
                }
                catch
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(service);
        }

        [Authorize(Roles = "employee")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var service = await this.serviceService.GetAsync(id);

                var serviceView = mapper.Map<ServiceUpdateViewModel>(service);

                return View(serviceView);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch
            {
                return Conflict();
            }
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "employee")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await this.serviceService.DeleteAsync(id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

SmartGarage/SmartGarage.Web/Views/Services/Create.cshtml
@model ServiceCreateViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Service</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                @foreach (var vehicleType in Model.VehicleTypes)
                {
                    <input name="types" type="checkbox" value="@vehicleType.VehicleTypeId" /> @vehicleType.Name<br />
                }
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SmartGarage/SmartGarage.Web/Views/Services/Delete.cshtml
@model ServiceUpdateViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Service</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ServiceId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SmartGarage/SmartGarage.Web/Views/Services/Details.cshtml
@model IPagedList<ServiceVehicleTypeViewModel>

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
} 

<h1>Details</h1>

<div>
    <h4>Service</h4>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.First().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().VehicleType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Currency)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VehicleType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Currency)
                </td>
            </tr>
            }
        </tbody>
    </table>
    @Html.PagedListPager(Model,
   page => Url.Action("Index", new { page }),
   new X.PagedList.Web.Common.PagedListRenderOptionsBase
   {
   DisplayLinkToIndividualPages = true,
   DisplayPageCountAndCurrentLocation = false,
   MaximumPageNumbersToDisplay = 10,
   LiElementClasses = new string[] { "page-item" },
   PageClasses = new string[] { "page-link" },
   })

</div>
<div>
    @if (User.IsInRole("employee"))
    {
        <a asp-action="Edit" asp-route-id="@Model.First().ServiceId">Edit</a> Write("| ");
        Write("| "); <a asp-action="Delete" asp-route-id="@Model.First().ServiceId">Delete</a> Write("| ");
    }
    <a asp-action="Index">Back to List</a>
</div>

SmartGarage/SmartGarage.Web/Views/Services/Edit.cshtml
@model ServiceUpdateViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Service</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ServiceId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                @foreach (var vehicleType in Model.VehicleTypes)
                {
                    <input name="types" type="checkbox" value="@vehicleType.VehicleTypeId" /> @vehicleType.Name<br />
                }
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SmartGarage/SmartGarage.Web/Views/Services/Index.cshtml
@model IPagedList<ServiceViewModel>
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Index", "Services", FormMethod.Get, new { @class = "col" }))
{
    <div class="row">
        <div class="col-2">
            <b class=" font-weight-bold">Service: </b>
        </div>
        <div class="col-2">
            @Html.TextBox("name")
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            <b class=" font-weight-bold">Price: </b>
        </div>
        <div class="col-2">
            @Html.TextBox("price")
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            <a class="btn btn-dark" asp-action="Index"> Back to full list</a>
        </div>
        <div class="col-2">
            <input type="submit" value="Filter" />
        </div>
    </div>
}

@if (SignInManager.IsSignedIn(User))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.First().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Currency)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        from @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Currency)
                    </td>
                    <td>
                        @if (item.VehicleTypes.Count == 0)
                        {
                            <a asp-action="" asp-route-id="" class="isDisabled" aria-disabled="true">Details</a>
                        }
                        else
                        {
                            <a asp-action="Details" asp-route-id="@item.ServiceId">Details</a>
                        }

                        @*@Html.ActionLink("Details", "Services", "Details", new { id = @item.ServiceId, VehicleType = item.VehicleType }, null)*@

                        @if (User.IsInRole("employee"))
                        {
                            Write("| ");<a asp-action="Edit" asp-route-id="@item.ServiceId">Edit</a>
                            Write("| "); <a asp-action="Delete" asp-route-id="@item.ServiceId">Delete</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @Html.PagedListPager(Model,
       page => Url.Action("Index", new { page }),
       new X.PagedList.Web.Common.PagedListRenderOptionsBase
       {
       DisplayLinkToIndividualPages = true,
       DisplayPageCountAndCurrentLocation = false,
       MaximumPageNumbersToDisplay = 10,
       LiElementClasses = new string[] { "page-item" },
       PageClasses = new string[] { "page-link" },
       })