SmartGarage/SmartGarage.Web/Models/VehicleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SmartGarage.Web.Models
{
    public class VehicleViewModel
    {
        public VehicleViewModel()
        {
            this.Visits = new List<int>();
        }

        public int VehicleId { get; set; }

        public string Vin { get; set; }

        public string RegistrationPlate { get; set; }

        public int OwnerId { get; set; }

        public int ModelId { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/yyyy}")]
        public DateTime Year { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime CreatedOn { get; set; }

        public int VehicleTypeId { get; set; }

        public string VehicleType { get; set; }

        public ICollection<int> Visits { get; set; }
    }
}

SmartGarage/SmartGarage.Web/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartGarage.Services.Contracts;
using SmartGarage.Services.DTO;
using SmartGarage.Web.Models;
using X.PagedList;

namespace SmartGarage.Web.Controllers
{
    [Authorize(Roles = "employee")]
    public class VehiclesController : Controller
    {
        private readonly IMapper mapper;
        private readonly IVehicleService vehicleService;
        private readonly IModelService modelService;
        private readonly IUserService userService;
        private readonly IVehicleTypeService vehicleTypeService;

        public VehiclesController(IMapper mapper, IVehicleService vehicleService, IModelService modelService, IUserService userService, IVehicleTypeService vehicleTypeService)
        {
            this.mapper = mapper;
            this.vehicleService = vehicleService;
            this.modelService = modelService;
            this.userService = userService;
            this.vehicleTypeService = vehicleTypeService;
        }

        public async Task<IActionResult> Index(int? page, string name)
        {
            var vehiclesViewModel = await FilterAsync(name, page);

            if (vehiclesViewModel == null)
                return NoContent(); 
            else
                return View(vehiclesViewModel);
        }

        private async Task<IPagedList<VehicleViewModel>> FilterAsync(string name, int? page)
        {
            if (name != null)
            {
                var vehiclesFiltered = await GetByCustomer(name, page);

                return vehiclesFiltered;
            }

            var vehiclesDto = await this.vehicleService.GetAllAsync();

            var vehiclesView = mapper.Map<ICollection<VehicleViewModel>>(vehiclesDto);
            var pageModel = await vehiclesView.ToPagedListAsync(page ?? 1, 10);

            return pageModel;
        }

        private async Task<IPagedList<VehicleViewModel>> GetByCustomer(string name, int? page)
        {
            var vehiclesDto = await this.vehicleService.GetByCustomer(name).ToListAsync();

            if (vehiclesDto.Count == 0)
                return null;

            var vehiclesView = mapper.Map<ICollection<VehicleViewModel>>(vehiclesDto);
            var pageModel = await vehiclesView.ToPagedListAsync(page ?? 1, 10);

            return pageModel;
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var itemDto = await this.vehicleService.GetAsync(id);

                var itemView = mapper.Map<VehicleDetailsViewModel>(itemDto);

                return View(itemView);
            }
            catch
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> Create()
        {
            var carModelDto = await this.modelService.GetAllAsync();
            var carModelView = mapper.Map<ICollection<CarModelViewModel>>(carModelDto);

            var ownerDto = await this.userService.GetAllAsync();
            var ownerView = mapper.Map<ICollection<UserGetViewModel>>(ownerDto);

            var vehicleTypeDto = await this.vehicleTypeService.GetAllAsync();
            var vehicleTypeView = mapper.Map<ICollection<VehicleTypeViewModel>>(vehicleTypeDto);

            ViewData["ModelId"] = new SelectList(carModelView, "ModelId", "Code");
            ViewData["OwnerId"] = new SelectList(ownerView, "Id", "Email");
            ViewData["VehicleTypeId"] = new SelectList(vehicleTypeView, "VehicleTypeId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken] 
        public async Task<IActionResult> Create([Bind("Vin,RegistrationPlate,OwnerId,ModelId,Year,VehicleTypeId")] VehicleCreateViewModel vehicleCreateViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var vehicleDto = mapper.Map<VehicleCreateDTO>(vehicleCreateViewModel);

                    var newVisitStatus = await this.vehicleService.CreateAsync(vehicleDto);

                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return NotFound();
                }
            }

            var carModelDto = await this.modelService.GetAllAsync();
            var carModelView = mapper.Map<ICollection<CarModelViewModel>>(carModelDto);

            var ownerDto = await this.userService.GetAllAsync();
            var ownerView = mapper.Map<ICollection<UserGetViewModel>>(ownerDto);

            var vehicleTypeDto = await this.vehicleTypeService.GetAllAsync();
            var vehicleTypeView = mapper.Map<ICollection<VehicleTypeViewModel>>(vehicleTypeDto);

            ViewData["ModelId"] = new SelectList(carModelView, "ModelId", "Code", vehicleCreateViewModel.ModelId);
            ViewData["OwnerId"] = new SelectList(ownerView, "Id", "Username", vehicleCreateViewModel.OwnerId);
            ViewData["VehicleTypeId"] = new SelectList(vehicleTypeView, "VehicleTypeId", "Name", vehicleCreateViewModel.VehicleTypeId);

            return View(vehicleCreateViewModel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var vehicleDto = await this.vehicleService.GetAsync(id);
                var vehicleView = mapper.Map<VehicleCreateViewModel>(vehicleDto);

                var carModelDto = await this.modelService.GetAllAsync();
                var carModelView = mapper.Map<ICollection<CarModelViewModel>>(carModelDto);

                var ownerDto = await this.userService.GetAllAsync();
                var ownerView = mapper.Map<ICollection<UserGetViewModel>>(ownerDto);

                var vehicleTypeDto = await this.vehicleTypeService.GetAllAsync();
                var vehicleTypeView = mapper.Map<ICollection<VehicleTypeViewModel>>(vehicleTypeDto);

                ViewData["ModelId"] = new SelectList(carModelView, "ModelId", "Code", vehicleView.ModelId);
                ViewData["OwnerId"] = new SelectList(ownerView, "Id", "Email", vehicleView.OwnerId);
                ViewData["VehicleTypeId"] = new SelectList(vehicleTypeView, "VehicleTypeId", "Name", vehicleView.VehicleTypeId);

                return View(vehicleView);
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VehicleId,Vin,RegistrationPlate,OwnerId,ModelId,Year,VehicleTypeId")] VehicleCreateViewModel vehicleCreateViewModel)
        {
            if (id != vehicleCreateViewModel.VehicleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var vehicleDto = mapper.Map<VehicleCreateDTO>(vehicleCreateViewModel);

                    await this.vehicleService.UpdateAsync(id, vehicleDto);
                }
                catch
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            var carModelDto = await this.modelService.GetAllAsync();
            var carModelView = mapper.Map<ICollection<CarModelViewModel>>(carModelDto);

            var ownerDto = await this.userService.GetAllAsync();
            var ownerView = mapper.Map<ICollection<UserGetViewModel>>(ownerDto);

            var vehicleTypeDto = await this.vehicleTypeService.GetAllAsync();
            var vehicleTypeView = mapper.Map<ICollection<VehicleTypeViewModel>>(vehicleTypeDto);

            ViewData["ModelId"] = new SelectList(carModelView, "ModelId", "Code", vehicleCreateViewModel.ModelId);
            ViewData["OwnerId"] = new SelectList(ownerView, "Id", "Email", vehicleCreateViewModel.OwnerId);
            ViewData["VehicleTypeId"] = new SelectList(vehicleTypeView, "VehicleTypeId", "Name", vehicleCreateViewModel.VehicleTypeId);

            return View(vehicleCreateViewModel);
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var vehicleDto = await this.vehicleService.GetAsync(id);

                var vehicleView = mapper.Map<VehicleViewModel>(vehicleDto);

                return View(vehicleView);
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
            catch
            {
                return Conflict();
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await this.vehicleService.DeleteAsync(id);
            }
            catch
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

SmartGarage/SmartGarage.Web/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartGarage.Services.Contracts;
using SmartGarage.Services.DTO;
using SmartGarage.Web.Models;
using X.PagedList;

namespace SmartGarage.Web.Controllers
{
    [Authorize(Roles = "employee")]
    public class VisitsController : Controller
    {
        private readonly IMapper mapper;
        private readonly IVisitService visitService;
        private readonly IServiceService serviceService;
        private readonly IVehicleService vehicleService;
        private readonly IVisitStatusService visitStatusService; 

        public VisitsController(IMapper mapper, IVisitService visitService, IServiceService serviceService, IVehicleService vehicleService, IVisitStatusService visitStatusService)
        {
            this.mapper = mapper;
            this.visitService = visitService;
            this.serviceService = serviceService;
            this.vehicleService = vehicleService;
            this.visitStatusService = visitStatusService;
        }

        public async Task<IActionResult> Index(int? page)
        {
            var itemsDto = await this.visitService.GetAllAsync();

            if (itemsDto.Count == 0)
            {
                return NoContent();
            }

            var itemsView = mapper.Map<ICollection<VisitViewModel>>(itemsDto);
            var pageModel = await itemsView.ToPagedListAsync(page ?? 1, 10);

            return View(pageModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var itemDto = await this.visitService.GetAsync(id);

                var itemView = mapper.Map<VisitFullReportViewModel>(itemDto);

                return View(itemView);
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var visitView = new VisitCreateViewModel();

            var servicesDto = await this.serviceService.GetAllAsync();
            var servicesView = mapper.Map<ICollection<ServiceViewModel>>(servicesDto);

            var vehiclesDto = await this.vehicleService.GetAllAsync();
            var vehiclesView = mapper.Map<ICollection<VehicleViewModel>>(vehiclesDto);

            //ViewData["ServiceId"] = new SelectList(servicesView, "ServiceId", "Name");
            ViewData["VehiclesId"] = new SelectList(vehiclesView, "VehicleId", "RegistrationPlate");

            visitView.DepartureDate = DateTime.Now;
            visitView.VisitServices = servicesView;

            return View(visitView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VisitCreateViewModel visitCreateViewModel,  List<int> services)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var visitDto = mapper.Map<VisitCreateDTO>(visitCreateViewModel);

                    var newVisit = await this.visitService.CreateAsync(visitDto, services);

                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return NotFound();
                }
            }

            return View(visitCreateViewModel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var visitDto = await this.visitService.GetAsync(id);
                var visitView = mapper.Map<VisitUpdateViewModel>(visitDto);

                var vehiclesDto = await this.vehicleService.GetAllAsync();
                var vehiclesView = mapper.Map<ICollection<VehicleViewModel>>(vehiclesDto);

                var visitStatusesDto = await this.visitStatusService.GetAllAsync();
                var visitStatusesView = mapper.Map<ICollection<VisitStatusViewModel>>(visitStatusesDto);

                var servicesDto = await this.serviceService.GetAllAsync();
                var servicesView = mapper.Map<ICollection<ServiceViewModel>>(servicesDto);

                ViewData["VehicleId"] = new SelectList(vehiclesView, "VehicleId", "RegistrationPlate", visitView.VehicleId);
                ViewData["VisitStatusId"] = new SelectList(visitStatusesView, "VisitStatusId", "Name", visitView.VisitStatusId);
                visitView.VisitServices = servicesView;

                return View(visitView);
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, VisitUpdateViewModel visitUpdateViewModel, List<int> services)
        {
            if (id != visitUpdateViewModel.VisitId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var visitDto = mapper.Map<VisitUpdateDTO>(visitUpdateViewModel);

                    await this.visitService.UpdateAsync(id, visitDto, services);
                }
                catch
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(visitUpdateViewModel);
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var visitDto = await this.visitService.GetAsync(id);

                var visitView = mapper.Map<VisitFullReportViewModel>(visitDto);

                return View(visitView);
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
            catch
            {
                return Conflict();
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await this.visitService.DeleteAsync(id);
            }
            catch
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

SmartGarage/SmartGarage.Web/Views/Vehicles/Create.cshtml
@model VehicleCreateViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Vin" class="control-label"></label>
                <input asp-for="Vin" class="form-control" />
                <span asp-validation-for="Vin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationPlate" class="control-label"></label>
                <input asp-for="RegistrationPlate" class="form-control" />
                <span asp-validation-for="RegistrationPlate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select> 
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelId" class="control-label"></label>
                <select asp-for="ModelId" class="form-control" asp-items="ViewBag.ModelId"></select> 
                <span asp-validation-for="ModelId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VehicleTypeId" class="control-label"></label>
                <select asp-for="VehicleTypeId" class="form-control" asp-items="ViewBag.VehicleTypeId"></select> 
                <span asp-validation-for="VehicleTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SmartGarage/SmartGarage.Web/Views/Vehicles/Delete.cshtml
@model VehicleViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationPlate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegistrationPlate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OwnerId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModelId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModelId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VehicleType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Visits)
        </dt>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="VehicleId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SmartGarage/SmartGarage.Web/Views/Vehicles/Details.cshtml
@model VehicleDetailsViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VehicleId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationPlate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegistrationPlate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OwnerId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Owner)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VehicleType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Visits)
        </dt>
        <dd class="col-sm-10">
            @foreach (var visit in Model.Visits)
            {
                <a asp-controller="Visits" asp-action="Details" asp-route-id="@visit">@visit </a>
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.VehicleId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SmartGarage/SmartGarage.Web/Views/Vehicles/Edit.cshtml
@model VehicleCreateViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="VehicleId" />
            <div class="form-group">
                <label asp-for="Vin" class="control-label"></label>
                <input asp-for="Vin" class="form-control" />
                <span asp-validation-for="Vin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationPlate" class="control-label"></label>
                <input asp-for="RegistrationPlate" class="form-control" />
                <span asp-validation-for="RegistrationPlate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>  
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelId" class="control-label"></label>
                <select asp-for="ModelId" class="form-control" asp-items="ViewBag.ModelId"></select>
                <span asp-validation-for="ModelId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VehicleTypeId" class="control-label"></label>
                <select asp-for="VehicleTypeId" class="form-control" asp-items="ViewBag.VehicleTypeId"></select>
                <span asp-validation-for="VehicleTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SmartGarage/SmartGarage.Web/Views/Vehicles/Index.cshtml
@model IPagedList<VehicleViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

@using (Html.BeginForm("Index", "Vehicles", FormMethod.Get))
{
    <b class=" font-weight-bold">Filter By Customer: </b>
    @Html.TextBox("name")
    <br />
    <input type="submit" value="Filter" />
    <a class="btn btn-outline-secondary btn-sm" asp-action="Index"> Back to full list</a>
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().VehicleId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Vin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().RegistrationPlate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().OwnerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().ModelId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().VehicleType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Visits)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.VehicleId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RegistrationPlate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModelId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VehicleType)
                </td>
                <td>
                    @foreach (var visit in item.Visits)
                    {
                        <a asp-controller="Visits" asp-action="Details" asp-route-id="@visit">@visit </a>
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.VehicleId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.VehicleId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.VehicleId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.PagedListPager(Model,
   page => Url.Action("Index", new { page }),
   new X.PagedList.Web.Common.PagedListRenderOptionsBase
   {
   DisplayLinkToIndividualPages = true,
   DisplayPageCountAndCurrentLocation = false,
   MaximumPageNumbersToDisplay = 10,
   LiElementClasses = new string[] { "page-item" },
   PageClasses = new string[] { "page-link" },
   })